config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get "home/index"
  get "home/login"
  get "home/pos_rank"
  get "home/neg_rank"
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/logout' => 'sessions#destroy', :as => :logout

end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/tweet_cache.rb
class TweetCache < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.screen_name = auth['info']['nickname']
      user.name = auth['info']['name']
      user.token = auth['credentials']['token']
      user.secret = auth['credentials']['secret']
    end
  end
 
  def self.get_twitter_client
    client = Twitter::Streaming::Client.new do |config|
      config.consumer_key        = Settings.twitter.consumer_key
      config.consumer_secret     = Settings.twitter.consumer_secret
      config.access_token        = self.token
      config.access_token_secret = self.secret
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  protect_from_forgery

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/home_controller.rb
class HomeController < BaseController

  before_filter :login_required, :except=> ["login"]

  def index
    if session[:user_id]
      @current_user = User.find_by_id(session[:user_id])
      unless @current_user
        redirect_to home_login_path
      end
    else
      redirect_to home_login_path
    end
  end

  def login
  end

  def pos_rank
   @best_positive_user = ""
   @best_positive_value = -10000
   point_user_dict = get_user_point_dict
   point_user_dict.each_key do |key|
     if @best_positive_value < point_user_dict[key].point
      @best_positive_value = point_user_dict[key].point
      @best_positive_user = point_user_dict[key]
     end
   end
  end

  def neg_rank
    @best_negative_user = ""
    @best_negative_value = 10000
    point_user_dict = get_user_point_dict
    point_user_dict.each_key do |key|
      if @best_negative_value > point_user_dict[key].point
        @best_negative_value = point_user_dict[key].point
        @best_negative_user = point_user_dict[key]
      end
    end
  end


private
  
  def login_required
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to home_login_path
    end
  end

  def get_user_point_dict
    user_point_dict = Hash.new
    tweets = get_twitter_client(@current_user).home_timeline({ count: 200 })
    tweets.each do |tweet|
      text = tweet.text
      user = tweet.user.screen_name

      cache = TweetCache.find_by_tw_id(tweet.id)
      pos_neg_point = 0
      if cache
        point = cache.posneg
      else
        point = get_pos_neg_point text
        cache = TweetCache.new
        cache.tw_id = tweet.id
        cache.posneg = point
        cache.save
      end
 
      if user_point_dict.include?(user)
        user_point_dict[user].point = point + user_point_dict[user].point
      else
        friend = Friend.new
        friend.name = tweet.user.screen_name
        friend.img_url = tweet.user.profile_image_url_https
        friend.point = point
        user_point_dict[user] = friend
      end
      
      if user_point_dict[user].tweet1.nil?
        user_point_dict[user].tweet1 = text
        user_point_dict[user].tweet1_link = "https://twitter.com/" + user + "/status/" + tweet.id.to_s
      elsif user_point_dict[user].tweet2.nil?
        user_point_dict[user].tweet2 = text
        user_point_dict[user].tweet2_link = "https://twitter.com/" + user + "/status/" + tweet.id.to_s
      end
      
      puts "negaposi : " + point.to_s
    end
    puts user_point_dict.inspect
    return user_point_dict
  end
  
  def get_pos_neg_point(text)
    begin
      url = URI.escape("https://lr.capio.jp/iminos/webapis/synana_k/1_1/?acckey=gi1syM3Feor8Ry4I&mode=tw_mode&sent=" + text)
  
      json = open(url) do |f|
        charset = f.charset # 文字種別を取得
        f.read # htmlを読み込んで変数htmlに渡す
      end

      result = JSON.parse(json)
      spn = result["results"][0]["spn"].to_i
      if spn == 1
        return 2
      elsif spn == 3
        return 1
      elsif spn == 0
        return 0
      elsif spn == 4
        return -1
      else
        return -2
      end
    rescue Exception => e
      puts e.message
      return 0
    end
  end

  def get_twitter_client(user)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Settings.twitter.consumer_key
      config.consumer_secret     = Settings.twitter.consumer_secret
      config.access_token        = user.token
      config.access_token_secret = user.secret
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def callback
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<p class="p_dan">みんなで幸せになろう！</p>
<p class="p_choise">ハッピーな友達からハッピーを分けてもらうか、不幸な友達にハッピーを分けてもらうか、選びましょう。</p>

<div id="content">
   <%= link_to image_tag('/img/do-happy.png', {}), home_pos_rank_path %>
   <%= link_to image_tag('/img/do-unhappy.png', {}), home_neg_rank_path %>
</div>

app/views/home/login.html.erb
<p class="p_choise">このアプリでは今最高に幸せな友達、一番落ち込んでいる友達がわかります。ハッピーな友達からは幸せを分けてもらいましょう！落ち込んでいる友達には幸せを分けて挙げましょう！</p>

<p class="p_dan">まずはTwitterで<br>ログインしましょう</p>

<div id="content">
  <%= link_to image_tag('/img/twitter-login.png', {}), '/auth/twitter' %>
</div>

app/views/home/neg_rank.html.erb
<p class="p_dan">あなたがこれから合うべき友達はこの人です。</p>
<img src="<%= @best_negative_user.img_url %>" width="150px" class="twitter_icon">

<!-- ネガの時 -->
<p class="p_choise">この友達と遊んで元気づけてあげましょう！</p>

<div id="content">
  <ul class="tweet_list">
    <% if @best_negative_user.tweet1 %>
      <li><%= link_to  @best_negative_user.tweet1[0..36], @best_negative_user.tweet1_link %></li>
    <% end %>
    <% if @best_negative_user.tweet2 %>
      <li><%= link_to @best_negative_user.tweet2[0..36], @best_negative_user.tweet2_link %></li>
    <% end %>
  </ul>
</div>

app/views/home/pos_rank.html.erb
<p class="p_dan">あなたがこれから合うべき友達はこの人です。</p>
<img src="<%= @best_positive_user.img_url %>" width="150px" class="twitter_icon">

<!- ポジの時 -->
<p class="p_choise">この友達と遊んでいっぱいハッピーを分けてもらいましょう！</p>

<div id="content">
  <ul class="tweet_list">
    <% if @best_positive_user.tweet1 %>
      <li><%= link_to @best_positive_user.tweet1[0..36], @best_positive_user.tweet1_link %></li>
    <% end %>
    <% if @best_positive_user.tweet2 %>
      <li><%= link_to @best_positive_user.tweet2[0..36], @best_positive_user.tweet2_link %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ポジネガフレンズ 友達と幸せを分かち合うアプリ</title>
  <meta name="viewport" content="width=320; initial-scale=1.0; minimum-scale=1.0; maximum-scale=2.0;" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<meta charset="UTF-8" />
	<link rel="stylesheet" href="css/bootstrap-ceru.min.css">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<%= stylesheet_link_tag("/css/style.css") %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1 class="title_var">幸せのお裾わけアプリ</h1>

<%= yield %>

<div id="footer">
  Copyright (C) divide happy.
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</body>
</html>